# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78f1d90892433de45cebae58145795c266bd6bd2ca6cd9436d9fd1f953930360040229877db8fec31bab069312a415308844f80fc7fb32cf9b25327afebd0755

test:
  secret_key_base: 5d3e31e550ce037a8f94fd84913411f166befd6b00d906c36d2d76252be70af83bb6b274003d352a32c3fbaf714119ba5bc39ff21be6475a4eaced6ec88dbc34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
